version: '3.7'
services:
  server:
    build: .
    ports: 
      - 5101:5101
    restart: always
    environment:
      - FLASK_ENV=production
    volumes:
      - ./params:/flaskapp/params

  front:
    depends_on: 
      - server
    build: ../frontend
    ports: 
      - 5173:5173
    restart: always
    volumes:
      - ../frontend/src:/src/src
    